# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export ZSH_CACHE_DIR=$HOME/.zsh

ZSH_THEME="spaceship"

plugins=(
	aws
	git
	zsh-autosuggestions
	zsh-completions
	golang
	dotenv
	docker
	docker-compose
	npm
	npx
	nvm
	python
    kubectl
)

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

# Aliases
alias clean-npm="find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +"

alias dc="docker-compose"
alias k="kubectl"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

export PATH="/usr/local/sbin:$PATH"

RPS1='$(kubectx_prompt_info)'
